In [3]:
#Question 1
import numpy as np
np.arange(start=2, stop=50, step=3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [15]:
#Question 2

arr = [[]]
arr = int(input("List"))




import numpy as np
arr = np.array([[1,5,6,7,0],[2,5,8,7,6]])

def selection_sort(x):
    for i in range(len(x)):
        swap = i + np.argmin(x[i:])
        (x[i], x[swap]) = (x[swap], x[i])
    return x

x = np.array([2, 1, 4, 3, 5])
selection_sort(x)

List345


array([1, 2, 3, 4, 5])

In [7]:
#Question 3

import numpy as np

a_1d = np.arange(3)
print(a_1d)


a_2d = np.arange(12).reshape((3, 4))
print(a_2d)


a_3d = np.arange(24).reshape((2, 3, 4))
print(a_3d)


#Dimensions of an array

print(a_1d.ndim)
# 1

print(type(a_1d.ndim))
# <class 'int'>

print(a_2d.ndim)
# 2

print(a_3d.ndim)
# 3


#Size of an array
print(a_1d.shape)

print(type(a_1d.shape))
# <class 'tuple'>

print(a_2d.shape)
# (3, 4)

print(a_3d.shape)
# (2, 3, 4)



[0 1 2]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
1
<class 'int'>
2
3
(3,)
<class 'tuple'>
(3, 4)
(2, 3, 4)


In [9]:
#Question 4

a_1d_array = np.array([1, 2, 3, 4])
print(a_1d_array)

reshaped_to_2d = np.reshape(a_1d_array, (-1, 2))
print(reshaped_to_2d)


[1 2 3 4]
[[1 2]
 [3 4]]
